export enum AuditAction {
  USER_REGISTER = 'USER_REGISTER',
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',
  USER_LOCK = 'USER_LOCK',
  USER_UNLOCK = 'USER_UNLOCK',
  PHONE_VERIFY = 'PHONE_VERIFY',
  TOKEN_REFRESH = 'TOKEN_REFRESH',
  PASSWORD_RESET = 'PASSWORD_RESET',
}

export enum VerificationPurpose {
  REGISTRATION = 'REGISTRATION',
  LOGIN = 'LOGIN',
  PHONE_CHANGE = 'PHONE_CHANGE',
  ACCOUNT_RECOVERY = 'ACCOUNT_RECOVERY',
}

export enum SystemRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  MODERATOR = 'MODERATOR',
  SUPPORT = 'SUPPORT',
  USER = 'USER',
  GUEST = 'GUEST',
}

export enum PermissionAction {
  CREATE = 'CREATE',
  READ = 'READ',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  ADMIN = 'ADMIN',
  MODERATE = 'MODERATE',
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  ASSIGN = 'ASSIGN',
  REVOKE = 'REVOKE',
}

export enum ResourceType {
  USER = 'USER',
  ROLE = 'ROLE',
  PERMISSION = 'PERMISSION',
  BOOKING = 'BOOKING',
  PAYMENT = 'PAYMENT',
  CONTENT = 'CONTENT',
  SYSTEM = 'SYSTEM',
  AUDIT = 'AUDIT',
  NOTIFICATION = 'NOTIFICATION',
  SUPPORT = 'SUPPORT',
}

export enum SubscriptionStatus {
  TRIAL = 'TRIAL',
  ACTIVE = 'ACTIVE',
  PAST_DUE = 'PAST_DUE',
  CANCELED = 'CANCELED',
  UNPAID = 'UNPAID',
  INCOMPLETE = 'INCOMPLETE',
  INCOMPLETE_EXPIRED = 'INCOMPLETE_EXPIRED',
}

export enum BusinessStaffRole {
  OWNER = 'OWNER',
  MANAGER = 'MANAGER',
  STAFF = 'STAFF',
  RECEPTIONIST = 'RECEPTIONIST',
}

export enum AppointmentStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELED = 'CANCELED',
  NO_SHOW = 'NO_SHOW',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  SUCCEEDED = 'SUCCEEDED',
  FAILED = 'FAILED',
  CANCELED = 'CANCELED',
  REFUNDED = 'REFUNDED',
}

export enum ClosureType {
  VACATION = 'VACATION',
  MAINTENANCE = 'MAINTENANCE',
  EMERGENCY = 'EMERGENCY',
  HOLIDAY = 'HOLIDAY',
  STAFF_SHORTAGE = 'STAFF_SHORTAGE',
  OTHER = 'OTHER',
}